### ISSUE TITLE
Todo list for SystemBase requirementes

### ISSUE THREAD

**Issue by jandrej** [JuLuSi/EEBO#5]
What should SystemBase (and thus every physics model) provide?
- [x] Access dry (not scaled/multiplied for transient case) Jacobian (Stiffness matrix in the linear case)
  - Assemble weak form into temporary matrix? (Although it is assembled at every timestep anyways, so order of operations matters!)
- [ ] Access mass matrix
- [ ] Control input interface
  - Modifiable at every timestep
- [ ] Set initial state
- [x] State/solution at every timestep
